In [21]:
import numpy as np

# incorrect - must be the transposé of u to be able to multiply vecteurs
u = np.array([[4], [2]])
print ("u = \n{}".format(u))

b = np.array([[-1, 2]])
print ("b = {}".format(b))

u = 
[[4]
 [2]]
b = [[-1  2]]


In [13]:
u@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [27]:
u = np.array([[4, 2]])
print ("u = {}".format(u))

b = np.array([[-1, 2]])
print ("b*T = \n{}".format(b.T))

print("Taille = {}".format(np.shape(u)))
print("Taille = {}".format(np.shape(b.T)))

u = [[4 2]]
b*T = 
[[-1]
 [ 2]]
Taille = (1, 2)
Taille = (2, 1)


In [29]:
b.T@u

array([[-4, -2],
       [ 8,  4]])

In [30]:
u@b.T

array([[0]])