# TP4 - Diagonalisation et SVD 

#### Les objectifs de ce quatrième TP sont de se familiariser avec
 - la diagonalisation de matrices (partie 1) - durée recommandée 1h30
 - la décomposition en valeurs singulières - SVD - et ses applications vues en cours (partie 2) - durée recommandée 1h30

#### Méthodologie
 - exécuter les cellules pour comprendre ce qui est programmé et comment
 - répondre aux questions en refaisant par vous-même
 - prendre le temps de travailler en dehors des séances pour assimiler les connaissances

In [29]:
## Importation des librairies nécessaires au TP
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import svd

# 1 - La diagonalisation par l'exemple

## 1.1 - Un exemple en exercice corrigé

On considère la matrice
$$
A=\displaystyle \left[\begin{array}{ccc}
1&2&2\\
0&0&0\\
0&2&2\\
\end{array}\right]
$$

pour laquelle nous allons numériquement

1. déterminer :
    - les éléments propres
    - les matrices $P$ (inversible) et $D$ (diagonale) requises pour la diagonalisation $A= P\,D\,P^{-1}$


2. vérifer un certain nombre de propriétés théoriques   

Il s'agit de la matrice de l'[exercice corrigé](https://moodle.caseine.org/pluginfile.php/143505/mod_resource/content/0/diagonalisation.pdf)
proposé sur le caséine de l'UE et pour laquelle toutes les questions ont été traitées analytiquement.
Vous pourrez donc comparer les résultats analytiques avec les résultats numériques.

#### En suivant la méthode analytique étape par étape

In [30]:
## Matrice A :
#################
A = np.array([[1,2,2],[0,0,0],[0,2,2]])
n = np.shape(A)[0]
print("A = \n{}".format(A))

A = 
[[1 2 2]
 [0 0 0]
 [0 2 2]]


In [31]:
## Ne pas chercher à comprendre cette fonction ##
#################################################
## Elle sert à afficher un polynome avec les coefficients des puissances de x
def Polynome_a_afficher(P):
    res = ""
    n = len(P)
    for i in range(len(P)):
        tmp = "(" + str(P[i]) + ")x^" + str(n-1-i)
        res = res + tmp
        if i < n-1 :
            res = res + " + "
    return res

In [32]:
## Polynôme caractéristique P_A = det(A-x*Id) et ses racines
###############################################################
##
## Calcul des coefficients du polynôme caractéristique dans la base canonique
P_A = - np.poly(A)
print("Les coefficients des puissances de x décroissantes du polynome sont :{}\n".format(P_A))
## Affichage du polynôme caractéristique 
print("Le polynôme est P_A(x) = {}\n".format(Polynome_a_afficher(P_A)))
##
## Calcul des racines du polynôme 
racines_P_A = np.roots(P_A)
## Affichage des racines du polynomes
deg_P_A = len(racines_P_A)
print("Les {} racines du polynôme caractéristique sont :".format(deg_P_A))
for i in range(deg_P_A):
    print("racine {} : {}".format(i+1,racines_P_A[i]))

Les coefficients des puissances de x décroissantes du polynome sont :[-1.  3. -2. -0.]

Le polynôme est P_A(x) = (-1.0)x^3 + (3.0)x^2 + (-2.0)x^1 + (-0.0)x^0

Les 3 racines du polynôme caractéristique sont :
racine 1 : 2.0
racine 2 : 1.0
racine 3 : 0.0


In [33]:
## Valeurs propres de la matrice A
##################################
valeurs_propres = np.linalg.eigvals(A)
print("Les {} valeurs propres de la matrice A sont :".format(len(valeurs_propres)))
for i in range(len(valeurs_propres)):
    print("Valeur propre {} : {}".format(i+1,valeurs_propres[i]))
## ATTENTION
## Remarquez que l'ordre n'est pas nécessairement le même que celui que nous avons choisi analytiquement... !!    

Les 3 valeurs propres de la matrice A sont :
Valeur propre 1 : 1.0
Valeur propre 2 : 2.0
Valeur propre 3 : 0.0


##### Questions
- Que cherchent à faire les commandes de la cellule ci-dessous?
- pourquoi l'exécution donne-t-elle le message d'erreur "Singular matrix" (NB : "singulière" veut dire "non-inversible")

In [34]:
## Vecteurs propres de la matrice A
###################################
## Pour la première valeur propre 
n = deg_P_A
M=A-racines_P_A[0]*np.eye(n)
B=np.zeros(n)
print("M = \n{}".format(M))
np.linalg.solve(M, B)

#Ici nous cherchons les vecteurs propres en fonction des valeurs de landa où nos créons la matrice P
#Nous reçevons le message "Singular Matrix", car c'est une matrice liée; le déterminant = 0
#Cette matrice est fait pour calculer une resultat unique, mais comme la déterminant du matrice est égale à 0, 
#nous avons une infinité de vecteurs possibles

M = 
[[-1.  2.  2.]
 [ 0. -2.  0.]
 [ 0.  2.  0.]]


LinAlgError: Singular matrix

#### En utilisant la commande "eig" de la librairie numpy (que nous ferons toujours par la suite)

In [35]:
## Calcul des éléments propres de la matrice A
###############################################
valeurs_propres,vecteurs_propres = np.linalg.eig(A)
print("Les valeurs propres de A sont {}".format(valeurs_propres))
print("Les vecteurs propres (en colonnes) de A sont\n{}".format(vecteurs_propres))

Les valeurs propres de A sont [1. 2. 0.]
Les vecteurs propres (en colonnes) de A sont
[[ 1.          0.89442719  0.        ]
 [ 0.          0.          0.70710678]
 [ 0.          0.4472136  -0.70710678]]


##### Question
A quoi correspond la vérification ci-dessous?

In [36]:
## Un exemple de vérification :
u_1 = vecteurs_propres[:, 0]
lambda_1 = valeurs_propres[0]
print("A*v = {}".format(A@u_1))
print("lambda*v = {}".format(lambda_1*u_1))
#Nous verifions que A fois le vecteur v = à landa fois le vecteur v
#et donc (A-landa*I)*v = 0 (vecteru nulle)
#Ceci veut donc dire que les vecteurs v déterminé sont juste

A*v = [1. 0. 0.]
lambda*v = [1. 0. 0.]


##### Question
Expliquer les valeurs affichées ci-dessous et leur signification

In [37]:
u_2 = vecteurs_propres[:, 1]
print(np.dot(u_1,u_2))
print(np.round(np.linalg.norm(u_2,2)))
## remarque : la commande np.round permet d'avoir un arrondi d'une valeur réelle
?np.round
#We rounded the decimal number up

0.8944271909999159
1.0


In [38]:
print(np.round(0.5837478201))

1.0


In [39]:
## Diagonalisation de la matrice A 
###################################
## Une fois effectuée la commande "valeurs_propres,vecteurs_propres = np.linalg.eig(A)"
D = np.diag(valeurs_propres)
P = vecteurs_propres
print("D = \n {}".format(D))
print("P = \n {}".format(P))
#Nous obtenons la matrice D des valeurs propres et la matrice P des vecteurs propres

D = 
 [[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 0.]]
P = 
 [[ 1.          0.89442719  0.        ]
 [ 0.          0.          0.70710678]
 [ 0.          0.4472136  -0.70710678]]


##### Questions
A quoi correspondent les deux vérifications ci-dessous?

In [40]:
## Un exemple de vérification :
print("{} est différent de 0".format(np.linalg.det(P)))
## Un exemple de vérification :
print(A-P@D@np.linalg.inv(P))
#Comme le determinant(P) est different de 0, P est donc inversible.
#D'apres la formule de diagonalisation, A - P*D*inv(P) doit être égale à une matrice nulle
#C'est notre cas

-0.3162277660168379 est différent de 0
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##### Questions
A quoi correspondent les deux vérifications ci-dessous?

In [46]:
## Un exemple de vérification :
print("{} = {}".format(np.linalg.det(A),np.linalg.det(D)))
#Le déterminant du matrice A = déterminant du matrice(D)
#Déterminant = produit des valeurs propres

## Un exemple de vérification :
print("{} = {}".format(np.trace(A),np.trace(D)))
#La trace du matrice A = trace du matrice D
#Trace = somme des valeurs propres

0.0 = 0.0
3 = 3.0


## 1.2 -------- EXERCICE - Diagonalisation de la matrice de Hilbert d'ordre 4
On rappelle (voir TP2) que la matrice de Hilbert d'ordre $n=4$ est
$$
\displaystyle 
H=\left(
\begin{array}{cccc}
1 & 1/2 & 1/3 & 1/4\\
1/2 & 1/3 & 1/4 & 1/5\\
1/3 & 1/4 & 1/5 & 1/6\\
1/4 & 1/5 & 1/6 & 1/7\\
\end{array}
\right)
$$

#### Question 1
Quelle propriété de la matrice $H$ permet de justifier sans calcul qu'elle est diagonalisable?

In [ ]:
# H est symétrique

#### Question 2
Calculer numériquement les valeurs propres de la matrice $H$

In [62]:
H = np.array([[1,1/2,1/3,1/4],[1/2,1/3,1/4,1/5],[1/3,1/4,1/5,1/6],[1/4,1/5,1/6,1/7]])
print("H = \n{}".format(H))

valeurs_propres,vecteurs_propres = np.linalg.eig(H)
print("Les valeurs propres de H sont {}".format(valeurs_propres))
#print("Les vecteurs propres (en colonnes) de A sont\n{}".format(vecteurs_propres))


H = 
[[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
Les valeurs propres de H sont [1.50021428e+00 1.69141220e-01 6.73827361e-03 9.67023040e-05]


#### Question 3
Déterminer numériquement les matrices $P$ et $D$ telles que $H= P\,D\,P^{-1}$

In [65]:
D1 = np.diag(valeurs_propres)
P1 = vecteurs_propres
print("D1 = \n {}".format(D1))
print("P1 = \n {}".format(P1))



D1 = 
 [[1.50021428e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.69141220e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 6.73827361e-03 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 9.67023040e-05]]
P1 = 
 [[ 0.79260829  0.5820757   0.17918629 -0.02919332]
 [ 0.45192312 -0.37050219 -0.74191779  0.32871206]
 [ 0.3224164  -0.50957863  0.10022814 -0.79141115]
 [ 0.25216117 -0.51404827  0.63828253  0.51455275]]


#### Question 4
Calculer le déterminant de la matrice $H$ à partir de ses valeurs propres

In [64]:
print("det(D1) = {} ".format(np.linalg.det(D1)))
print("det(H) = {} ".format(np.linalg.det(H)))

det(D1) = 1.653439153439608e-07 
det(H) = 1.6534391534390412e-07 


#### Question 5
Lister toutes les propriétés de la matrice de passage $P$ en séparant :
- celles obligatoires 
- celle(s) que l'on peut imposer 

In [ ]:
#Obligatoires:
# P doit être Inversible
# La taille du matrice (P) = taille du matrice (H) 
# Matrice carré


#Celles que l'on peut imposer:
# Si la matrice H est symétrique alors P peut être orthogonale (trans(P)=inv(P))

#### Question 6
Vérifier par un calcul numérique que les 4 vecteurs colonnes de la matrice $P$ forment une base orthonormale de $\mathbb{R}^4$.

In [123]:
print("transposée de P1 = \n{}".format(P1.T))

inv_P1 = np.linalg.inv(P1)
print("inv de P1 = \n{}".format(inv_P1))

#print(P1.T == inv_P1)

print("Comme le transposée de P1 = l'inv de P1, la matrice P forment une base orhtonormale de R^4")

transposée de P1 = 
[[ 0.79260829  0.45192312  0.3224164   0.25216117]
 [ 0.5820757  -0.37050219 -0.50957863 -0.51404827]
 [ 0.17918629 -0.74191779  0.10022814  0.63828253]
 [-0.02919332  0.32871206 -0.79141115  0.51455275]]
inv de P1 = 
[[ 0.79260829  0.45192312  0.3224164   0.25216117]
 [ 0.5820757  -0.37050219 -0.50957863 -0.51404827]
 [ 0.17918629 -0.74191779  0.10022814  0.63828253]
 [-0.02919332  0.32871206 -0.79141115  0.51455275]]
Comme le transposée de P1 = l'inv de P1, la matrice P forment une base orhtonormale de R^4


In [80]:
inv_P1 = np.linalg.inv(P1)
print("P1*inv_P1 = \n{}".format(np.dot(P1, inv_P1)))
#Since the values are approximations, the symétrical values are approxmately 0

print("P1*T.P1 = \n{}".format(np.dot(P1, P1.T)))

P1*inv_P1 = 
[[ 1.00000000e+00 -2.72939247e-17 -1.01010815e-17  3.58516663e-17]
 [ 1.49822439e-16  1.00000000e+00 -5.23360555e-17 -6.46380795e-17]
 [ 7.48548249e-17 -2.46827265e-17  1.00000000e+00 -3.08203661e-17]
 [ 5.20142965e-17 -1.25449656e-16  2.22120231e-16  1.00000000e+00]]
P1*T.P1 = 
[[ 1.00000000e+00 -4.87258409e-17  2.76721331e-16 -2.18194945e-16]
 [-4.87258409e-17  1.00000000e+00 -1.01196402e-15  3.94346703e-16]
 [ 2.76721331e-16 -1.01196402e-15  1.00000000e+00  9.35686798e-16]
 [-2.18194945e-16  3.94346703e-16  9.35686798e-16  1.00000000e+00]]


In [143]:
for i in range (4):
    for j in range(4):
        u_i = P1[:,i]
        u_j = P1[:,j]
        print("Le produit scalaire de: \n {} et {} \n = {}".format(i+1,j+1,np.dot(u_i,u_j)))

Le produit scalaire de: 
 1 et 1 
 = 1.0000000000000002
Le produit scalaire de: 
 1 et 2 
 = -2.220446049250313e-16
Le produit scalaire de: 
 1 et 3 
 = -1.6653345369377348e-16
Le produit scalaire de: 
 1 et 4 
 = -5.551115123125783e-17
Le produit scalaire de: 
 2 et 1 
 = -2.220446049250313e-16
Le produit scalaire de: 
 2 et 2 
 = 1.0000000000000002
Le produit scalaire de: 
 2 et 3 
 = 1.3877787807814457e-17
Le produit scalaire de: 
 2 et 4 
 = 1.6653345369377348e-16
Le produit scalaire de: 
 3 et 1 
 = -1.6653345369377348e-16
Le produit scalaire de: 
 3 et 2 
 = 1.3877787807814457e-17
Le produit scalaire de: 
 3 et 3 
 = 1.0
Le produit scalaire de: 
 3 et 4 
 = -1.9290125052862095e-15
Le produit scalaire de: 
 4 et 1 
 = -5.551115123125783e-17
Le produit scalaire de: 
 4 et 2 
 = 1.6653345369377348e-16
Le produit scalaire de: 
 4 et 3 
 = -1.9290125052862095e-15
Le produit scalaire de: 
 4 et 4 
 = 1.0000000000000002


#### Question 7
Vérifier par un calcul numérique que la matrice $P$ est orthogonale.

In [90]:
#A est symétrique alors P peut être orthogonale: trans(P) = inv(P)
# P.T - inv P
P_orth = P1.T-np.linalg.inv(P1)
print(P_orth)

print("Distance entre trans(P1)-inv(P1) = {}".format(np.linalg.norm(P_orth)))
#La valeur obtenue est environ égale à 0

[[-2.22044605e-16  3.33066907e-16  2.22044605e-16  5.55111512e-17]
 [ 0.00000000e+00 -2.22044605e-16 -2.22044605e-16 -2.22044605e-16]
 [-2.77555756e-17 -6.66133815e-16  1.29063427e-15 -9.99200722e-16]
 [-3.29597460e-16  1.38777878e-15 -5.55111512e-16 -1.22124533e-15]]
Distance entre trans(P1)-inv(P1) = 2.702467572270385e-15


# 2 - Décomposition en valeurs singulières - SVD

Vous pouvez accèder aux [notes de cours sur la SVD ici](https://moodle.caseine.org/pluginfile.php/181980/mod_resource/content/1/SVD.pdf).

## 2.1 - SVD & conditionnement de la matrice de Hilbert

In [117]:
## En reprenant l'exercice 1.2, on définit la matrice de Hilbert d'ordre 4
n=4
H=np.zeros((n,n))
for i in range(n):
    for j in range(n):
        H[i,j]=1./((i+1)+(j+1)-1) 
## Decomposition en valeurs singulières de H 
U, sigma, trans_V = svd(H)
##
print("\n-> Matrice orthogonale U")
print(U)
#
S = np.diag(sigma)
#
print("\n-> Matrice diagonale S")
print(S)
#
print("\n-> Matrice orthogonale transposée de V")
print(trans_V)


-> Matrice orthogonale U
[[-0.79260829  0.5820757  -0.17918629 -0.02919332]
 [-0.45192312 -0.37050219  0.74191779  0.32871206]
 [-0.3224164  -0.50957863 -0.10022814 -0.79141115]
 [-0.25216117 -0.51404827 -0.63828253  0.51455275]]

-> Matrice diagonale S
[[1.50021428e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.69141220e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 6.73827361e-03 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 9.67023040e-05]]

-> Matrice orthogonale transposée de V
[[-0.79260829 -0.45192312 -0.3224164  -0.25216117]
 [ 0.5820757  -0.37050219 -0.50957863 -0.51404827]
 [-0.17918629  0.74191779 -0.10022814 -0.63828253]
 [-0.02919332  0.32871206 -0.79141115  0.51455275]]


##### Questions
A quoi correspondent les trois vérifications ci-dessous?

In [141]:
## Un exemple de vérification :
print("\n Vérification 1 :")
print(np.round(U@U.T))

#Verfication d'une matrice identité pour confirmer son orthogonalité

## Un exemple de vérification :
print("\n Vérification 2 :")
print(np.round(tV@tV.T))

#Verification d'une matrice identité pour confirmer son orthogonalité

## Un exemple de vérification :
print("\n Vérification 3 :")
print(np.round(H-U@S@tV))

#Verification de comment le determinant(H) est different de 0, P est donc inversible.
#D'apres la formule de diagonalisation, H - U*S*trans(V) doit être égale à une matrice nulle
#C'est notre cas


 Vérification 1 :
[[ 1. -0.  0.  0.]
 [-0.  1. -0. -0.]
 [ 0. -0.  1. -0.]
 [ 0. -0. -0.  1.]]

 Vérification 2 :
[[ 1. -0.  0.  0.]
 [-0.  1.  0.  0.]
 [ 0.  0.  1. -0.]
 [ 0.  0. -0.  1.]]

 Vérification 3 :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [121]:
## Calcul de la valeur du conditionnement de la matrice H
Conditionnement_H_python= np.linalg.cond(H)
print("Le conditionnement obtenu directemement en python est : {} ".format(Conditionnement_H_python))


Le conditionnement obtenu directemement en python est : 15513.73873892924 


##### Question
Calculer le conditionnement de la matrice de Hilbert d'ordre 4 par la formule du cours
$
cond(H) = \sigma_1/\sigma_4
$
où
- $\sigma_1$ est la plus grande valeur singulière de $H$ 
- $\sigma_4$ est la plus petite valeur singulière de $H$

Puis vérifier votre résultat avec la valeur obtenue par la commande `np.linalg.cond(H)`

In [ ]:
## A VOUS DE FAIRE

##### Question
Expliquer pourquoi la matrice de Hilbert est mal conditionnée

In [ ]:
## A VOUS DE FAIRE

## 2.2 - Comprendre la SVD "à la main" - exemple de la matrice de Hilbert

On se propose dans cette section de faire la décomposition en valeurs singulières de la matrice de Hilbert "à la main", c'est à dire de suivre les étapes proposées dans le cours.

Vous pouvez aussi vous remémorer ces étapes et les formules dans l'[exercice corrigé sur la SVD](https://moodle.caseine.org/pluginfile.php/180381/mod_resource/content/2/Seance.06.pdf)

In [ ]:
## Décomposition en valeurs singulières - La théorie de la SVD pour H
#####################################################################
## 1] Diagonalisation de la matrice B définie par tH * H
## ---> Obtention des matrices S et V
#####################################
## Calcul de la matrice B = tH * H
B = H.T@H
## Calcul des éléments propres de B
valeurs_propres_B,vecteurs_propres_B = np.linalg.eig(B)
D_B = np.diag(valeurs_propres_B)
P_B = vecteurs_propres_B
##
## Avec les notations de la SVD de H, on en déduit :
## 1) les valeurs singulières de H qui dont les racines carrées de valeurs propres de B
##    ce qui permet de construire la matrice S
##    Remarque : on nomme cette matrice S_H pour la comparer à la matrice S obtenue à la section 2.1
S_H = np.sqrt(D_B)
## 2) la matrice V (notée ici V_H) definie comme la matrice de passage de la diagonalisation de B
V_H = P_B

In [ ]:
##############################################################
## 2] Diagonalisation de la matrice C définie par H * tH
## ---> Vérification des valeurs singulières
############################################
## Calcul de la matrice C = H * tH
C = H@H.T
## Calcul des éléments propres de C
valeurs_propres_C,vecteurs_propres_C = np.linalg.eig(C)
D_C = np.diag(valeurs_propres_C)
## On peut alors vérifier que les valeurs propres de B et de C sont bien identiques
## Elles sont contenues dans les matrices diagonales D_B et D_C
## et permettent donc de définir les valeurs singulières comme leurs racines carrées
print(np.round(D_B-D_C))

In [ ]:
##############################################################
## 3] Obtention de la matrice U
################################
## Cette matrice est donnée par une formule dans le cours...
## Remarque : on nomme cette matrice U_H pour la comparer à la matrice U obtenue à la section 2.1
U_H=np.zeros((n,n))
for j in range(n):
    U_H[:,j]=H@V_H[:,j]/S_H[j,j]

####  Question 1
Vérifier la diagonalisation de la matrice $B$ par un calcul numérique, c'est à dire que $B=P_B D_B P_B^{-1}$

#### Question 2
Vérifier que la matrice $U_H$ est bien une matrice de passage pour la diagonalisation de $C$, c'est à dire que $C = U_H\,D_C\, U_H^{-1}$

#### Question 3
Vérifier la décomposition en valeurs singulières de la matrice $H$, c'est à dire que $H = U_H\, S_H\, ^t\hspace{-0.2mm}V_H$

#### Question 4
Comparer les matrices 
$$(U,S,\,^t\hspace{-0.2mm}V)$$ obtenues à la section 2.1 par la commande `svd(H)`
avec les matrices
$$(U_H,S_H,\,^t\hspace{-0.2mm}V_H)$$ obtenues ci-dessus "à la main".

* La SVD obtenue par la commande `svd(H)` est-elle la même que celle obtenue par vos calculs?
* Quelles différences observez-vous et pourquoi sont-elles cohérentes ?

#### Testez votre compréhension en répondant aux questions suivantes 

En ayant défini les matrices $B=\, ^t\hspace{-0.7mm}H\,H$ et $C=H\,^t\hspace{-0.7mm}H$ :
- Quelles propriétés possèdent les valeurs propres des matrices $B$ et $C$?
- Comment définit-on les valeurs singulières de la matrice $H$?
- Comment sont définies les matrices $U$, $S$ et $V$ qui forment la décomposition de $H$ en valeurs singulières, c'est à dire sous la forme $H=U\,S\,^t\hspace{-0.2mm}V$?
- Quelle(s) propriété(s) possèdent les matrices $U$ et $V$?
- La décomposition de $H$ en valeurs singulières est-elle unique?  (expliquez votre réponse)

#### $\color{red}{\textbf{Et pour ceux qui ont tout compris...}}$
- Vérifier et expliquer pourquoi les valeurs propres et les valeurs singulières de la matrice $H$ sont égales

## 2.3 - SVD de Sam le lapin (illustration du cours)

In [ ]:
## Afichage de l'image originale de SAM
A = np.loadtxt("sam.csv", delimiter="\t", dtype=int)
fig, ax = plt.subplots()
ax.imshow(A, cmap="Greys_r")

In [ ]:
## SVD de la matrice A
U, sigma, tV = svd(A)
B = np.zeros_like(A)
## Nombre de valeurs singulières considérées pour la reconstuction de Sam le lapin dans {1,2,..., n =512}
s=10
for i in range(s):
    ## Attention : en python np.array(U[:,i]]) donne les valeurs de la colonne i-1 du tableau U
    ## c'est a dire la colonne i de la matrice U
    ## mais en tableau mono-dimensionnel et donc en ligne alors qu'on le veut en vecteur colonne
    colonne_i_U = np.array([U[:,i]]).T
    ligne_i_tV = np.array([tV[i,:]])
    ## Création de la matrice B approchée de A
    B = B + sigma[i] * colonne_i_U @ ligne_i_tV
    fig, ax = plt.subplots()
    #print('Reconstruction pour {} valeurs singulières'.format(i))
    plt.title(f'Reconstruction pour {i+1} valeurs singulières\n')
    ax.imshow(B, cmap="Greys_r")

##### Question 1
A partir de combien de valeurs singulières (c'est à dire la valeur de `s`) reconnait-on bien Sam le lapin ?

##### Question 2
Utiliser le [cours](https://moodle.caseine.org/pluginfile.php/181980/mod_resource/content/1/SVD.pdf) pour déterminer le taux de compression théorique, c'est à dire le rapport 

$$\frac{\mbox{mémoire utilisée pour stocker A}}{\mbox{mémoire utilisée pour stocker B}}$$
en fonction de la valeur de `s`